#
###################################
# Site wide configuration
####################################
#
title: VeereshElango
email: ecveer@gmail.com
description: Data Scientist & Developer
url: https://veereshelango.github.io


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Stockholm
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Veeresh Elango
  avatar: suit.jpg
  job: "Data Scientist @ Scania"
  bio: "I am fascinated to explore different machine learning algorithms and admire them by applying it."
  email: ecveer@gmail.com
  disqus-shortname: veereshelango
  twitter: veereshelango
  facebook: veereshelango
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: veereshelango
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: veereshelango
  skype: #username
  xing: #username
  instagram: veereshelango
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
